### ISSUE TITLE
swagger support and restful support

### ISSUE THREAD

**Issue by wangkai1994** [hulklab/yago#38]
yago not support  swaggo ... api doc framework?

and i can't write restful api because i can't define same url even i use different action

**Comment by wangkai1994** [comment]
@xdlaw

**Comment by xdlaw** [comment]
@wangkai1994  We will solve restful bugs in recent versions, maybe you can try the function of swagger by [Yapi](https://github.com/YMFE/yapi) . Or PR is welcome.

**Comment by xdlaw** [comment]
@wangkai1994 Yago v1.6.0 has been released, you can try it. It may be incompatible with the previous，but it better now. We will be pleased to answer any questions you may have. 
Ex:
![image](https://user-images.githubusercontent.com/19724637/86195945-a2d27480-bb84-11ea-96f4-676646fbb1e1.png)
