### ISSUE TITLE
HttpThird的logInterceptor在下载大文件的时候会oom

### ISSUE THREAD

**Issue by schecterdamien** [hulklab/yago#69]
https://github.com/hulklab/yago/blob/a87ad7aa46f5d14b0b64c4dedbc4775f0d72040c/base/basethird/http.go#L506

这里会把所有的response都读到内存，如果是下载大文件的话，很快就会被oom掉，踩坑了，哈哈

**Comment by KowloonZh** [comment]
我把获取 resp 的处理挪到开启了日志开关的里面是否能满足？

**Comment by schecterdamien** [comment]
提了pr哈，https://github.com/hulklab/yago/pull/72
